language: python

python:
  - "3.8"

install:
  - pip install -U pip setuptools
  - pip install -r mycity/mycity/deploy_tools/requirements.txt
  - pip install --no-deps -r mycity/mycity/deploy_tools/requirements_no_deps.txt

script:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
  - cd mycity && sh run_tests.sh
  - cd mycity/deploy_tools && python deploy_tools.py -p

branches:
  only:
    - gh-pages
    - /.*/ # test all branches

after_success:
  - cd $TRAVIS_BUILD_DIR && codecov
